name = "WriteDocx"
uuid = "d049ceea-54ee-41d7-a26f-ba29db3b6599"
authors = ["Julius Krumbiegel <julius.krumbiegel@gmail.com> and contributors"]
version = "1.0.0"

[deps]
EnumX = "4e289a0a-7415-4d19-859d-a7e5c4648b56"
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"

[compat]
EnumX = "1"
EzXML = "1"
MacroTools = "0.5"
OrderedCollections = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
